
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Migrations run against the direct DB — DATABASE_URL points at the
    // transaction pooler (port 6543) which doesn't support migrate ops.
    url: env("DIRECT_URL"),
  },
});
