
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { config as loadEnv } from "dotenv";
import { defineConfig, env } from "prisma/config";

// Match Next.js env precedence: .env.local overrides .env for local CLI runs.
// CI / production set DIRECT_URL directly in the environment, so loadEnv
// is a no-op there.
loadEnv({ path: ".env.local", override: true });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  engine: "classic",
  datasource: {
    // Migrations run against the direct DB — DATABASE_URL points at the
    // transaction pooler (port 6543) which doesn't support migrate ops.
    url: env("DIRECT_URL"),
  },
});
