export const COOL_SEASON_PROMPT = `COOL-SEASON GRASS CLIMATE SUITABILITY — When a cool-season grass (tall fescue, Kentucky bluegrass, perennial ryegrass) is detected in USDA Zone 8 or warmer (ZIP codes in lower AL, MS, GA, LA, FL, SC coast, TX, AZ, southern CA), note the climate limitation:
- Tall fescue: viable in Zone 8 with supplemental irrigation and summer stress management, but at the edge of its adaptation; acknowledge the higher maintenance demands in hot climates
- Kentucky bluegrass: poor performer south of Zone 7 in most of the country; in Zone 8+ the homeowner should be aware this grass will struggle in summer
- Perennial ryegrass: annual in most of Zone 8+ (used for winter overseeding on warm-season lawns, not as a permanent turf)
- Do NOT refuse to give recommendations, but briefly acknowledge the climate challenge as part of setting realistic expectations

FALL NITROGEN SPLIT APPLICATIONS — Cool-season grasses (KBG, tall fescue, fine fescue) in Zones 5–7:
- ALWAYS split fall N into two applications: (1) Early September (Labor Day window): 0.5–1.0 lbs N per 1,000 sq ft; (2) Late October/November (Thanksgiving window, before ground freezes): 0.5–1.0 lbs N per 1,000 sq ft
- Do NOT apply the full seasonal fall N budget in a single early September application — this approach promotes excessive top growth and leaching before winter
- A pre-emergent + fall N overlap in September is fine: apply pre-emergent for weed control AND the first split of N for turf health at the same time
- PRODUCT SELECTION FOR EARLY SEPTEMBER SPLIT: Do NOT recommend Scotts WinterGuard 32-0-10 or similar "WinterGuard"-branded products for the early September application — these are formulated for the late-season (October/November) application. For the Labor Day window, recommend a SLOW-RELEASE nitrogen source: prefer MESA (Methylene-Extended Sulfur-coated Ammonium — e.g., Lebanon ProScape 24-0-11 with MESA), PCU (polymer-coated urea — e.g., Lesco/SiteOne polymer-coated 32-0-10 SR formulations), or SCU (sulfur-coated urea). Do NOT default to IBDU as a slow-release recommendation — IBDU is largely UNAVAILABLE at retail and through online channels; MESA/PCU/SCU are the realistic homeowner-accessible slow-release options. NOTE: Milorganite 6-4-0 delivers only 6% N — to apply 1 lb N requires applying 16.7 lbs of product per 1,000 sqft (e.g., 3+ bags for a 5,000 sqft lawn) which is impractical; prefer a more concentrated slow-release product (MESA, PCU, SCU) for the September application. Reserve WinterGuard or high-K products for the Thanksgiving window.
- AERATION + PRE-EMERGENT TASK SCHEDULING: When creating scheduled tasks in the JSON output, set aeration task scheduledStartDays 0–7 (first week of September) and pre-emergent task scheduledStartDays 14–28 (2–4 weeks later). NEVER schedule aeration and pre-emergent within the same 7-day window — they must be separated by at least 14 days in the task schedule.
- Pre-emergent herbicide injury risk on cool-season overseeding: if fall overseeding is also planned, prodiamine and pendimethalin pre-emergent applications will injure or kill new seed. ALWAYS flag this incompatibility when recommending both overseeding and pre-emergent in fall.
- FALL OVERSEEDING-vs-PRE-EMERGENT TRADEOFF MUST BE EXPLICITLY ADDRESSED for cool-season scenarios in August-October when ANY of the following are true: (a) the profile or notes mention thin spots, bare areas, sparse turf, or thinning; (b) the profile or notes document Poa annua, crabgrass, or other weed pressure that would normally trigger fall pre-emergent; (c) the grass type is a bunch-type cool-season grass (tall fescue, perennial ryegrass) — these grasses do not self-thicken and require periodic overseeding. In these cases, the fall pre-emergent recommendation MUST include a sentence acknowledging that applying pre-emergent precludes overseeding for the season, and frame this as a deliberate choice for the homeowner ("If you would prefer to overseed this fall to address the thin areas, skip the pre-emergent this season and plan to control Poa annua with post-emergent in spring; pre-emergent and overseeding are incompatible except with siduron/Tupersan."). Do NOT silently recommend fall pre-emergent on a thin or Poa-pressured cool-season lawn without surfacing this choice.`;
