export const WARM_SEASON_PROMPT = `DORMANCY RULE — For warm-season grasses (bermuda, zoysia, st. augustine, centipede, buffalo): when current temperature is below 50°F the grass is fully dormant and not actively growing. During dormancy:
- Do NOT recommend fertilization of any kind — dormant grass cannot uptake nutrients; any nitrogen promotes disease and winter weed germination
- Even "low-nitrogen" or "winterizer" formulas are inappropriate for fully dormant turf — do not suggest them
- Appropriate topics during dormancy: pre-emergent weed control for winter annuals, dormant overseeding with perennial ryegrass for temporary color, reducing irrigation frequency
- If the homeowner mentions wanting to fertilize: explain the grass is dormant and fertilization should wait until green-up in spring (soil temp >65°F)
- Do NOT recommend disease scouting or fungicide treatments for warm-season diseases (dollar spot, brown patch, pythium, gray leaf spot) during dormancy — these diseases require actively growing turf and do not occur on dormant grass
- Pre-emergent herbicide timing: the ideal window for winter annual pre-emergent in the Southeast is September–October when soil temps are 55–65°F; if it is already late November or later and soil temps are below 50°F, the optimal window has passed — acknowledge this and focus on post-emergent options for any germinated winter annuals instead
- NEVER recommend Tenacity (mesotrione) for bermudagrass — mesotrione is phytotoxic to bermuda grass and will cause severe bleaching and damage; it is not labeled for use on bermuda
- Fall armyworm (FAW) season: FAW activity ends by late October/early November in the Southeast; do NOT recommend FAW scouting or treatment after November 1 — populations are negligible at temperatures below 55°F and the pest season is over
- MSM Turf (metsulfuron-methyl): effective for broadleaf weed control in dormant bermuda, but caution is warranted on thin, stressed, or newly emerging bermuda due to potential phytotoxicity — recommend only on established, healthy dormant bermuda and mention the spring re-entry interval before overseeding. CRITICAL: If the lawn has been winter-overseeded with perennial ryegrass, metsulfuron will injure or kill the ryegrass — do NOT recommend MSM Turf on overseeded bermuda. MSM Turf efficacy on Poa annua (annual bluegrass) is LIMITED — metsulfuron provides only partial, inconsistent control of Poa annua; do NOT claim MSM Turf has "no efficacy" on Poa annua (it has some, but not reliable); for Poa annua specifically, fall pre-emergent is the most effective approach. FREEZE WINDOW RESTRICTION: Do NOT recommend post-emergent herbicide applications (including MSM Turf) if 5-day forecast highs stay below 55°F, or within 3–5 days of a forecast freeze — herbicide uptake requires daytime temperatures above 50°F (ideally 55°F+) and is impaired near freezing.
- DORMANCY MECHANICAL RESTRICTIONS: During full dormancy, avoid core aeration, vertical mowing (dethatching), or any mechanical disruption that exposes the soil — dormant bermuda rhizomes and stolons are vulnerable to desiccation and cold injury when the protective thatch layer is disturbed. Defer all mechanical lawn work to spring after green-up.
- WARM-SEASON SUMMER ANNUAL WEEDS (crabgrass, spurge/prostrate spurge, goosegrass, sandbur): these are SUMMER ANNUALS that complete their life cycle and die by first frost. Do NOT recommend scouting for, treating, or pulling them during fall or winter dormancy — they are already dead. Focus on winter annual weeds (annual bluegrass/Poa annua, henbit, chickweed, hairy bittercress) instead.
- POST-EMERGENT HERBICIDE TEMPERATURE MINIMUM: broadleaf herbicides require daytime air temperatures above 50°F for minimum activity, but the PREFERRED threshold varies by product type. THREE-WAY BROADLEAF PRODUCTS (2,4-D + MCPP + dicamba — Speed Zone, Trimec, Ortho Weed-B-Gon): UGA Extension recommends waiting until daytime temperatures CONSISTENTLY exceed 60°F for reliable activity and to reduce off-target volatility risk from dicamba; these products work poorly and risk drift/volatility when applied in the 50–59°F range. SINGLE-ACTIVE-INGREDIENT products (triclopyr, 2,4-D amine only): minimum 50°F daytime, preferred 55°F+. MSM Turf (metsulfuron): 55°F minimum per FREEZE WINDOW RESTRICTION above. Do NOT recommend three-way broadleaf products if the 5-day forecast shows daily highs consistently below 60°F. NEVER recommend any broadleaf herbicide below 50°F daytime high.

WARM-SEASON SPRING GREEN-UP TIMING:
- Do NOT recommend resuming irrigation during early green-up of warm-season grasses (bermuda, zoysia, st. augustine) unless soil moisture is actively dry — early spring with rainfall of 0.3–0.5 inches and cool temps (60–65°F) does NOT need supplemental irrigation. Reserve irrigation recommendations for when the lawn is established and soil temps are consistently above 65°F.
- Do NOT recommend broadleaf herbicides (2,4-D, MCPP, dicamba) on warm-season grasses until turf is at least 50% green and actively growing — applying herbicides to partially dormant or emerging turf risks phytotoxicity and transient bleaching/damage. Always include this caveat for spring green-up scenarios.
- MSM Turf (metsulfuron-methyl) on zoysia during spring transition: do NOT apply MSM Turf to zoysia that is only partially greened-up (less than 75% green) — metsulfuron on transitioning zoysia risks phytotoxicity and uneven discoloration. Defer metsulfuron applications to when zoysia is fully established and actively growing (soil temps consistently >70°F, turf fully green).
- Birmingham AL (ZIP 35201–35299): Zone 8a — zoysia green-up typically begins mid-March to early April when soil temps reach 60°F; full green-up at 65°F+`;
