import Link from "next/link";
import { Logo } from "@/components/Logo";
import { Footer } from "@/components/Footer";

export const metadata = { title: "Terms of Use – Yard Analyzer" };

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col bg-white">
      <nav className="flex items-center justify-between px-6 py-4 max-w-6xl mx-auto w-full border-b border-gray-100">
        <Link href="/" className="flex items-center gap-1">
          <Logo className="h-7 w-auto" />
          <span className="text-lg font-bold text-green-700">Yard Analyzer</span>
        </Link>
      </nav>

      <main className="flex-1 max-w-3xl mx-auto px-6 py-12 w-full">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Use</h1>
        <p className="text-sm text-gray-400 mb-10">Last updated: June 10, 2026</p>

        <div className="prose prose-gray max-w-none space-y-8 text-gray-700 text-sm leading-relaxed">

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">1. Acceptance of Terms</h2>
            <p>By creating an account, clicking &ldquo;I Accept,&rdquo; or using Yard Analyzer, you agree to these Terms of Use and acknowledge that you have read and understood them. If you do not agree, do not use the service.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">2. Description of Service</h2>
            <p>Yard Analyzer is an AI-assisted lawn care platform that helps homeowners diagnose lawn issues, track yard health, and receive personalized care recommendations. The service includes photo analysis, schedule management, weather integration, and email notifications.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">3. AI-Generated Advice — Important Disclaimer</h2>
            <p className="font-medium text-gray-900">All recommendations generated by Yard Analyzer are produced by artificial intelligence and are provided for informational and educational purposes only. They are not professional horticultural, agricultural, landscaping, or agronomic advice.</p>
            <ul className="list-disc pl-5 space-y-2 mt-3">
              <li>AI recommendations may be incorrect, incomplete, outdated, or inappropriate for your specific lawn, soil, climate, or conditions.</li>
              <li>Following AI-generated advice may result in lawn damage, plant death, wasted product, or financial loss. You assume all risk.</li>
              <li>Product amounts, application rates, spreader settings, and timing are estimates only. Always follow the manufacturer&rsquo;s label instructions, which are legally binding. Never apply any product in a manner inconsistent with its labeling.</li>
              <li>Yard Analyzer does not guarantee any results. Outcomes depend on factors entirely outside our control including weather, soil conditions, existing lawn health, and the accuracy of information you provide.</li>
              <li>If you are uncertain about a recommendation, consult a licensed lawn care professional or your local university extension service before acting on it.</li>
            </ul>
            <p className="mt-3">By using this service you acknowledge that you are solely responsible for all decisions about what products to apply, when, and in what quantities.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">4. Your Account</h2>
            <p>You are responsible for maintaining the security of your account credentials. You must provide accurate information when registering. You may not share your account with others or create multiple accounts for the same person.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">5. User Content</h2>
            <p>By uploading photos or entering data into Yard Analyzer, you grant us a non-exclusive license to use that content solely to provide the service. We do not sell your content to third parties. You retain ownership of everything you upload.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">6. Payments and Billing</h2>
            <p>Some features require a paid subscription. Billing terms, pricing, and refund policies are presented at the time of purchase. You may cancel at any time; access continues until the end of the current billing period. For billing questions, contact us at <a href="mailto:contact@yardanalyzer.com" className="text-green-600 hover:underline">contact@yardanalyzer.com</a>.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">7. Acceptable Use</h2>
            <p>You agree not to misuse the service, attempt to access other users&rsquo; data, reverse engineer any part of the platform, or use the service for any unlawful purpose.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">8. Third-Party Services</h2>
            <p>Yard Analyzer integrates with third-party providers including Anthropic (AI analysis), OpenWeatherMap (weather data), Supabase (data storage), and Resend (email delivery). Use of these services is subject to their own terms and privacy policies.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">9. Limitation of Liability</h2>
            <p className="uppercase font-semibold text-gray-900 text-xs tracking-wide">To the maximum extent permitted by applicable law:</p>
            <p className="mt-2">YARD ANALYZER AND ITS OPERATORS SHALL NOT BE LIABLE FOR ANY DAMAGE TO YOUR LAWN, GARDEN, PROPERTY, OR PLANTS; ANY FINANCIAL LOSS FROM PRODUCT PURCHASES MADE BASED ON APP RECOMMENDATIONS; ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES; OR ANY LOSS ARISING FROM YOUR RELIANCE ON AI-GENERATED CONTENT, WHETHER OR NOT WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
            <p className="mt-2">Our total liability for any claim arising from your use of the service shall not exceed the total amount you paid us in the twelve (12) months immediately preceding the event giving rise to the claim, or $10.00, whichever is greater.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">10. Indemnification</h2>
            <p>You agree to indemnify and hold harmless Yard Analyzer and its operators from any claims, damages, or expenses (including reasonable legal fees) arising from your use of the service, your violation of these terms, or your application of any AI-generated lawn care recommendations.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">11. Changes to These Terms</h2>
            <p>We may update these terms from time to time. We will notify registered users of material changes by email or by requiring re-acceptance within the app. Continued use of the service after changes take effect constitutes acceptance of the updated terms.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">12. Contact</h2>
            <p>Questions about these terms? Email us at <a href="mailto:contact@yardanalyzer.com" className="text-green-600 hover:underline">contact@yardanalyzer.com</a>.</p>
          </section>

        </div>
      </main>

      <Footer />
    </div>
  );
}
