import Link from "next/link";
import { Logo } from "@/components/Logo";
import { Footer } from "@/components/Footer";
import { PublicHamburger } from "@/components/PublicHamburger";

export const metadata = { title: "Terms of Use | Yard Analyzer" };

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col bg-white">
      <nav className="flex items-center justify-between px-6 py-4 max-w-6xl mx-auto w-full border-b border-gray-100">
        <Link href="/" className="flex items-center gap-2">
          <Logo className="h-6 w-auto" />
          <span className="text-gray-300">|</span>
          <span className="text-[26px] leading-none font-bold text-green-700">Yard Analyzer</span>
        </Link>
        <PublicHamburger />
      </nav>

      <main className="flex-1 max-w-3xl mx-auto px-6 py-12 w-full">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Use</h1>
        <p className="text-sm text-gray-400 mb-10">Last updated: June 23, 2026</p>

        <div className="prose prose-gray max-w-none space-y-8 text-gray-700 text-sm leading-relaxed">

          <p>Yard Analyzer (the &ldquo;Service&rdquo;) is operated by Null State Software LLC (&ldquo;we,&rdquo; &ldquo;us,&rdquo; or &ldquo;our&rdquo;). These Terms of Use govern your access to and use of the Service.</p>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">1. Acceptance of Terms</h2>
            <p>By creating an account, clicking &ldquo;I Accept,&rdquo; or using the Service, you agree to these Terms of Use and acknowledge that you have read and understood them. If you do not agree, do not use the Service.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">2. Description of Service</h2>
            <p>Yard Analyzer is an automated lawn care platform that helps homeowners diagnose lawn issues, track yard health, and receive personalized care recommendations. The service includes photo analysis, schedule management, weather integration, and email notifications.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">3. Automated Recommendations: Important Disclaimer</h2>
            <p className="font-medium text-gray-900">All recommendations generated by Yard Analyzer are produced by automated software and are provided for informational and educational purposes only. They are not professional horticultural, agricultural, landscaping, or agronomic advice.</p>
            <ul className="list-disc pl-5 space-y-2 mt-3">
              <li>Automated recommendations may be incorrect, incomplete, outdated, or inappropriate for your specific lawn, soil, climate, or conditions.</li>
              <li>Following these automated recommendations may result in lawn damage, plant death, wasted product, or financial loss. You assume all risk.</li>
              <li>Product amounts, application rates, spreader settings, and timing are estimates only. Always follow the manufacturer&rsquo;s label instructions, which are legally binding. Never apply any product in a manner inconsistent with its labeling.</li>
              <li>We do not guarantee any results. Outcomes depend on factors entirely outside our control including weather, soil conditions, existing lawn health, and the accuracy of information you provide.</li>
              <li>If you are uncertain about a recommendation, consult a licensed lawn care professional or your local university extension service before acting on it.</li>
            </ul>
            <p className="mt-3">By using this service you acknowledge that you are solely responsible for all decisions about what products to apply, when, and in what quantities.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">4. Your Account</h2>
            <p>You are responsible for maintaining the security of your account credentials. You must provide accurate information when registering. You may not share your account with others or create multiple accounts for the same person.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">5. User Content</h2>
            <p>By uploading photos or entering data into Yard Analyzer, you grant us a non-exclusive license to use that content solely to provide the service. We do not sell your content to third parties. You retain ownership of everything you upload.</p>
          </section>

          <section id="billing">
            <h2 className="text-lg font-semibold text-gray-900 mb-2">6. Payments and Billing</h2>
            <p>Some features require a paid subscription. Current pricing is shown on the <Link href="/pricing" className="text-green-600 hover:underline">pricing page</Link>. Billing is handled by Stripe; the charges that appear on your statement are subject to Stripe&rsquo;s terms in addition to ours.</p>

            <h3 className="text-base font-semibold text-gray-900 mt-5 mb-2">6.1 Free trial</h3>
            <p>New accounts include a 21-day free trial of the Basic plan. No payment method is required to start the trial. If you do not subscribe before the trial ends, your account becomes read-only and your data is retained for 30 days before deletion.</p>

            <h3 className="text-base font-semibold text-gray-900 mt-5 mb-2">6.2 Monthly vs. annual billing</h3>
            <ul className="list-disc pl-5 space-y-2 mt-2">
              <li><strong>Monthly</strong> plans bill once a month and can be canceled or downgraded at any time.</li>
              <li><strong>Annual</strong> plans are a 12-month commitment. You pay for the full year up front in exchange for a roughly two-month discount. The commitment is the reason for the discount.</li>
            </ul>

            <h3 className="text-base font-semibold text-gray-900 mt-5 mb-2">6.3 Tier changes (Basic ↔ Plus ↔ Professional)</h3>
            <ul className="list-disc pl-5 space-y-2 mt-2">
              <li><strong>Tier upgrades</strong> take effect immediately. You are charged the prorated difference between your current plan and the new plan for the remainder of the current billing period. Your renewal date does not change.</li>
              <li><strong>Tier downgrades on monthly</strong> take effect immediately. The unused portion of the current month is credited toward your next bill. No refund is issued to your payment method; the credit is applied automatically to upcoming invoices.</li>
              <li><strong>Tier downgrades on annual</strong> take effect at the end of your current annual term. You paid for a full year of the higher tier, and you keep using it through that full year. On your renewal date, your plan switches to the lower tier. We do not take features away mid-term and we do not issue partial-year credits.</li>
              <li>If a downgrade would put you over the new plan&rsquo;s yard limit, you will be asked to choose which yard(s) to keep before the change is confirmed. For immediate downgrades the remaining yards are archived now; for deferred (annual) downgrades the remaining yards are archived on the renewal date. Archived yards stay in your account and are automatically restored if you upgrade to a plan that supports them again. You can permanently delete archived yards yourself from the settings screen.</li>
            </ul>

            <h3 className="text-base font-semibold text-gray-900 mt-5 mb-2">6.4 Switching between monthly and annual</h3>
            <ul className="list-disc pl-5 space-y-2 mt-2">
              <li><strong>Monthly → annual</strong> takes effect immediately. You are charged the annual amount today, less a credit for unused days of the current month. Your new annual term runs for 12 months from that date.</li>
              <li><strong>Annual → monthly</strong> (same plan) takes effect at the end of your current annual term. The switch is scheduled, and your account continues at the annual plan until then. This is because annual is a 12-month commitment.</li>
              <li><strong>Annual → monthly that upgrades your plan</strong> (for example, Basic annual to Plus monthly) lets you pick on the billing screen: (a) upgrade your plan immediately at the annual rate and switch to monthly at renewal, or (b) keep your current plan and current annual term, and schedule the new plan plus monthly billing to start at renewal. You pick which one fits.</li>
              <li><strong>Annual → monthly that downgrades your plan</strong> (for example, Plus annual to Basic monthly) always waits for renewal. You keep using the plan you paid for through the full annual term. On the renewal date your plan switches to the new lower tier on monthly billing. We do not take features away or issue partial credits for time you already paid for.</li>
              <li>You can cancel a scheduled switch from the billing screen at any time before it takes effect.</li>
            </ul>

            <h3 className="text-base font-semibold text-gray-900 mt-5 mb-2">6.5 Cancellation and data retention</h3>
            <ul className="list-disc pl-5 space-y-2 mt-2">
              <li>You may cancel at any time from the billing screen. Cancellation takes effect at the end of your current billing period; you keep access until then.</li>
              <li>After cancellation, your data is retained for 30 days. You can re-subscribe within that window and your yards, photos, and analyses will be restored.</li>
              <li>Annual subscribers who cancel mid-term keep access through the original renewal date. No partial-year refunds are issued.</li>
            </ul>

            <h3 className="text-base font-semibold text-gray-900 mt-5 mb-2">6.6 Failed payments and past-due accounts</h3>
            <p>If a renewal charge fails, we will retry the payment per Stripe&rsquo;s default schedule and email you to update your payment method. If the charge is not resolved within Stripe&rsquo;s retry window, your account moves to a past-due status with limited access. You may restore full access by updating your payment method at any time.</p>

            <h3 className="text-base font-semibold text-gray-900 mt-5 mb-2">6.7 Price changes</h3>
            <p>If we change pricing, currently active subscribers continue at their existing price through the end of their current term. New pricing applies at the next renewal, and we will notify you by email at least 14 days before the change takes effect.</p>

            <h3 className="text-base font-semibold text-gray-900 mt-5 mb-2">6.8 Questions</h3>
            <p>For billing questions, contact us at <a href="mailto:contact@nullstatesoftware.llc" className="text-green-600 hover:underline">contact@nullstatesoftware.llc</a>.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">7. Acceptable Use</h2>
            <p>You agree not to misuse the service, attempt to access other users&rsquo; data, reverse engineer any part of the platform, or use the service for any unlawful purpose.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">8. Third-Party Services</h2>
            <p>Yard Analyzer integrates with third-party providers including Anthropic (automated analysis), OpenWeatherMap (weather data), Supabase (data storage), and Resend (email delivery). Use of these services is subject to their own terms and privacy policies.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">9. Limitation of Liability</h2>
            <p className="uppercase font-semibold text-gray-900 text-xs tracking-wide">To the maximum extent permitted by applicable law:</p>
            <p className="mt-2">NULL STATE SOFTWARE LLC AND ITS AFFILIATES SHALL NOT BE LIABLE FOR ANY DAMAGE TO YOUR LAWN, GARDEN, PROPERTY, OR PLANTS; ANY FINANCIAL LOSS FROM PRODUCT PURCHASES MADE BASED ON APP RECOMMENDATIONS; ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES; OR ANY LOSS ARISING FROM YOUR RELIANCE ON AUTOMATED RECOMMENDATIONS, WHETHER OR NOT WE HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.</p>
            <p className="mt-2">Our total liability for any claim arising from your use of the service shall not exceed the total amount you paid us in the twelve (12) months immediately preceding the event giving rise to the claim, or $10.00, whichever is greater.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">10. Indemnification</h2>
            <p>You agree to indemnify and hold harmless Null State Software LLC and its affiliates from any claims, damages, or expenses (including reasonable legal fees) arising from your use of the Service, your violation of these terms, or your application of any automated lawn care recommendations.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">11. Governing Law</h2>
            <p>These Terms are governed by the laws of the State of Delaware, without regard to its conflict of laws principles. Any dispute arising out of or related to these Terms or the Service shall be brought exclusively in the state or federal courts located in Delaware.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">12. Changes to These Terms</h2>
            <p>We may update these terms from time to time. We will notify registered users of material changes by email or by requiring re-acceptance within the app. Continued use of the Service after changes take effect constitutes acceptance of the updated terms.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">13. Contact</h2>
            <p>Questions about these terms? Email us at <a href="mailto:contact@nullstatesoftware.llc" className="text-green-600 hover:underline">contact@nullstatesoftware.llc</a>.</p>
            <p className="mt-2">Mailing address:</p>
            <address className="not-italic mt-1 text-gray-700">
              Null State Software LLC<br />
              8 The Green, STE B<br />
              Dover, DE 19901<br />
              United States
            </address>
          </section>

        </div>
      </main>

      <Footer />
    </div>
  );
}
