import Link from "next/link";
import Image from "next/image";
import { Footer } from "@/components/Footer";

export const metadata = { title: "Terms of Use – Yard Buddy" };

export default function TermsPage() {
  return (
    <div className="min-h-screen flex flex-col bg-white">
      <nav className="flex items-center justify-between px-6 py-4 max-w-6xl mx-auto w-full border-b border-gray-100">
        <Link href="/" className="flex items-center gap-1">
          <Image src="/gnome-buddy.png" alt="Yard Buddy" width={28} height={28} className="rounded-full scale-x-[-1]" />
          <span className="text-lg font-bold text-green-700">Yard Buddy</span>
        </Link>
      </nav>

      <main className="flex-1 max-w-3xl mx-auto px-6 py-12 w-full">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Terms of Use</h1>
        <p className="text-sm text-gray-400 mb-10">Last updated: June 10, 2026</p>

        <div className="prose prose-gray max-w-none space-y-8 text-gray-700 text-sm leading-relaxed">

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">1. Acceptance of Terms</h2>
            <p>By creating an account or using Yard Buddy, you agree to these Terms of Use. If you do not agree, please do not use the service.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">2. Description of Service</h2>
            <p>Yard Buddy is an AI-assisted lawn care platform that helps homeowners diagnose lawn issues, track yard health, and receive personalized care recommendations. The service includes photo analysis, schedule management, weather integration, and email notifications.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">3. AI-Generated Content Disclaimer</h2>
            <p>Recommendations provided by Yard Buddy are generated by AI and are for informational purposes only. They do not constitute professional horticultural, agricultural, or landscaping advice. Always use your own judgment when applying products to your lawn. Yard Buddy is not responsible for outcomes resulting from following AI-generated recommendations.</p>
            <p className="mt-2">Product amounts, spreader settings, and application timing are estimates. Follow all manufacturer instructions and local regulations when applying any lawn care products.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">4. Your Account</h2>
            <p>You are responsible for maintaining the security of your account credentials. You must provide accurate information when registering. You may not share your account with others or create multiple accounts for the same person.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">5. User Content</h2>
            <p>By uploading photos or entering data into Yard Buddy, you grant us a non-exclusive license to use that content solely to provide the service. We do not sell your content to third parties. You retain ownership of everything you upload.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">6. Payments and Billing</h2>
            <p>Some features may require a paid subscription. Billing terms, pricing, and refund policies will be presented at the time of purchase. You may cancel your subscription at any time; access continues until the end of the current billing period. For billing questions, contact us at <a href="mailto:contact@yardbuddy.com" className="text-green-600 hover:underline">contact@yardbuddy.com</a>.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">7. Acceptable Use</h2>
            <p>You agree not to misuse the service, attempt to access other users' data, reverse engineer any part of the platform, or use the service for any unlawful purpose.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">8. Third-Party Services</h2>
            <p>Yard Buddy integrates with third-party providers including Anthropic (AI analysis), OpenWeatherMap (weather data), Supabase (data storage), and Resend (email delivery). Use of these services is subject to their own terms and privacy policies.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">9. Limitation of Liability</h2>
            <p>To the maximum extent permitted by law, Yard Buddy and its operators shall not be liable for any indirect, incidental, or consequential damages arising from your use of the service. Our total liability for any claim shall not exceed the amount you paid us in the twelve months preceding the claim.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">10. Changes to These Terms</h2>
            <p>We may update these terms from time to time. We will notify registered users of material changes by email. Continued use of the service after changes take effect constitutes acceptance of the updated terms.</p>
          </section>

          <section>
            <h2 className="text-lg font-semibold text-gray-900 mb-2">11. Contact</h2>
            <p>Questions about these terms? Email us at <a href="mailto:contact@yardbuddy.com" className="text-green-600 hover:underline">contact@yardbuddy.com</a>.</p>
          </section>

        </div>
      </main>

      <Footer />
    </div>
  );
}
