"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import Link from "next/link";
import { Logo } from "@/components/Logo";
import { acceptTermsAction } from "@/app/_actions/terms";

export default function AcceptTermsPage() {
  const router = useRouter();
  const [accepted, setAccepted] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function handleAccept() {
    if (!accepted) return;
    setSubmitting(true);
    setError(null);
    const result = await acceptTermsAction();
    if (!result.ok) {
      setError("Something went wrong. Please try again.");
      setSubmitting(false);
      return;
    }
    router.push("/dashboard");
  }

  return (
    <div className="min-h-screen flex flex-col bg-white">
      <nav className="flex items-center px-6 py-4 max-w-6xl mx-auto w-full border-b border-gray-100">
        <Link href="/" className="flex items-center gap-2">
          <Logo className="h-6 w-auto" />
          <span className="text-gray-300">|</span>
          <span className="text-[26px] leading-none font-bold text-green-700">Yard Analyzer</span>
        </Link>
      </nav>

      <main className="flex-1 flex items-start justify-center px-6 py-12">
        <div className="w-full max-w-lg">
          <h1 className="text-2xl font-bold text-gray-900 mb-2">Updated Terms of Use</h1>
          <p className="text-gray-500 text-sm mb-8">Please review and accept our terms before continuing.</p>

          <div className="rounded-xl border border-gray-200 bg-gray-50 p-5 space-y-4 text-sm text-gray-700 mb-6">
            <div>
              <p className="font-semibold text-gray-900 mb-1">Automated Recommendations</p>
              <p>Yard Analyzer&rsquo;s recommendations are generated by automated software and are for informational purposes only. They are not professional lawn care advice. Following them may result in lawn damage or financial loss. You assume all risk.</p>
            </div>
            <div>
              <p className="font-semibold text-gray-900 mb-1">No Liability for Lawn Damage</p>
              <p>Yard Analyzer is not liable for any damage to your lawn, garden, plants, or property arising from your use of the service or reliance on these automated recommendations. Always verify product amounts against the manufacturer&rsquo;s label before applying.</p>
            </div>
            <div>
              <p className="font-semibold text-gray-900 mb-1">Your Responsibility</p>
              <p>You are solely responsible for all decisions about what products to apply, when, and in what quantities. When in doubt, consult a licensed lawn care professional.</p>
            </div>
            <Link href="/terms" target="_blank" className="inline-block text-green-600 hover:underline font-medium text-xs">
              Read the full Terms of Use →
            </Link>
          </div>

          <div className="flex items-start gap-3 mb-6">
            <input
              id="accept"
              type="checkbox"
              className="mt-0.5 h-4 w-4 rounded border-gray-300 accent-green-600"
              checked={accepted}
              onChange={(e) => setAccepted(e.target.checked)}
            />
            <label htmlFor="accept" className="text-sm text-gray-700 cursor-pointer">
              I have read and agree to the{" "}
              <Link href="/terms" target="_blank" className="text-green-600 hover:underline font-medium">
                Terms of Use
              </Link>
              , including the automated advice disclaimer and limitation of liability.
            </label>
          </div>

          {error && <p className="text-sm text-red-500 mb-4">{error}</p>}

          <button
            onClick={handleAccept}
            disabled={!accepted || submitting}
            className="w-full bg-green-600 hover:bg-green-700 disabled:opacity-50 disabled:cursor-not-allowed text-white font-semibold py-2.5 px-4 rounded-lg transition-colors"
          >
            {submitting ? "Saving…" : "I Accept and Continue to Yard Analyzer"}
          </button>
        </div>
      </main>
    </div>
  );
}
