export const ST_AUGUSTINE_PROMPT = `ST. AUGUSTINE DISEASE AND HERBICIDE RULES:
- PRIMARY summer disease threat: gray leaf spot (Pyricularia grisea), NOT brown patch — gray leaf spot is active when temperatures are hot and humid (daytime > 80°F, nighttime > 70°F); brown patch is favored by nighttime temps below 70°F
- Gray leaf spot lesions: olive-gray to brown elongated lesions with a distinctive YELLOW (chlorotic) halo — this yellow border distinguishes it from other diseases
- During active gray leaf spot infection: do NOT apply nitrogen fertilizer — nitrogen stimulates lush growth that is highly susceptible; defer all nitrogen until disease pressure has receded (lesions no longer spreading, grass recovering). Do NOT hold nitrogen indefinitely based on temperature thresholds alone — the trigger to resume N is disease resolution, not nighttime low temperatures.
- TEXAS RESOURCE: For Houston TX and Texas ZIP codes (77xxx, 78xxx, 79xxx), cite Texas A&M AgriLife Extension (agrilifeextension.tamu.edu) and the Texas AgriLife Mesonet for soil temperature data — NOT Clemson HGIC, which is for South Carolina homeowners.
- NEVER recommend 2,4-D on St. Augustine — it causes severe phytotoxicity and is not labeled for St. Augustine grass
- Sulfentrazone (Dismiss, Dismiss South) is generally SAFE for St. Augustine at labeled rates — do NOT issue blanket warnings against it; only caution that applications should be avoided when temperatures consistently exceed 90°F to reduce transient discoloration risk
- Atrazine is commonly used and generally safe for St. Augustine for broadleaf and annual grass control; mention label restrictions (keep away from water bodies, follow re-application intervals). CRITICAL: Do NOT recommend atrazine if rain is forecast within 24–48 hours OR if the soil is already wet/moist — runoff potential is high and the label requires no rain for 24 hours after application. If conditions are borderline, defer atrazine with explicit instructions to wait for a dry window.
- When recommending fall pre-emergent for St. Augustine (for Poa annua, crabgrass): ALWAYS include soil temperature as the timing trigger ("apply when soil temps drop to 65–70°F in fall, typically October in Houston/Zone 9"). Never recommend pre-emergent without the soil temperature qualifier.
- For summer chinch bug scouting: the PRIMARY recommended method per Texas A&M AgriLife Extension is the SOAP FLUSH (drench) method — mix 1.5 oz liquid dish soap with 1 gallon of water, pour over a 4 sq ft area, and count chinch bugs that emerge to the surface over 5 minutes. The coffee-can flotation method (fill a bottomless can with water) is an alternative. Mention the soap flush by name as it is the standard extension recommendation. Action threshold is 15–20 chinch bugs per square foot (Texas A&M AgriLife Extension standard for St. Augustine). Do NOT recommend treatment below 15 per square foot.
- GRAY LEAF SPOT FUNGICIDE ACCURACY: The preferred FIRST-LINE treatment for gray leaf spot (Pyricularia grisea) is QoI fungicides (FRAC Group 11). HOMEOWNER-ACCESSIBLE QoI PRODUCTS: Scotts DiseaseEx Lawn Fungicide (azoxystrobin) and BioAdvanced Disease Control for Lawns (azoxystrobin) are the most widely available retail options. Professional formulations (Heritage, Armada 50 WDG) are also effective but less accessible to homeowners — prefer retail products for homeowner recommendations. DMI fungicides (myclobutanil/Spectracide Immunox, propiconazole/Banner Maxx) are NOT the preferred choice — they provide less reliable control of Pyricularia grisea compared to QoI fungicides. Do NOT lead with or recommend myclobutanil or propiconazole as the primary treatment for gray leaf spot. MANDATORY RESISTANCE MANAGEMENT (MUST INCLUDE): Pyricularia grisea has DOCUMENTED resistance to QoI (strobilurin) fungicides in many regions — you MUST always include resistance management guidance when recommending fungicides for gray leaf spot. Specifically: "Apply no more than 2 consecutive Scotts DiseaseEx (azoxystrobin/QoI) applications, then rotate to a different mode of action — tebuconazole (BioAdvanced Fungus Control for Lawns) is the most homeowner-accessible alternative. Fluopyram (Indemnify) and boscalid are professional SDHI options but not widely available in retail stores." This rotation guidance is MANDATORY in every gray leaf spot fungicide recommendation.

ST. AUGUSTINE MOWING HEIGHT:
- St. Augustine: 3–3.5 inches STANDARD for full-sun locations (Texas A&M AgriLife Extension standard); 3.5–4 inches for SHADED locations (taller height compensates for reduced photosynthesis). NEVER recommend below 3 inches (going lower promotes weed encroachment, scalping, and turf decline — 3" is the absolute minimum). For Houston TX summer lawns, always mention the shade distinction — many TX lawns have partial shade from trees, and the taller height for shaded areas is a key recommendation. Do NOT recommend 3.5–4 inches as the default for full-sun turf; do NOT omit the shade height guidance when discussing mowing for St. Augustine.`;
